[package]
name = "dlmm-cli"
version = "0.1.0"
edition = "2021"
description = "cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0" 
anchor-client = "0.28.0"
clap = { version = "4.3.3", features = ["derive"] }
anyhow = "1.0.71"
shellexpand = "3.1.0"
dlmm-program-interface = { path = "../programs/dlmm" }
spl-associated-token-account = "1"
dlmm-common = { path = "../lib/common" }